version: "3.5"

services:
    app:
        container_name: fb_ingenieria
        image: fb_ingenieria
        build: .
        user: node
        command: sh -c '${DEPLOY_CMD}'
        working_dir: /usr/node/app
        volumes:
            - ./:/usr/node/app
        ports:
            - 8080:8080
            - 9005:9005
