version: "3.3"

services:
    wordpress:
        container_name: fbingenieria
        image: wordpress
        ports:
            - 5000:80
        volumes:
            - .:/var/www/html/
        environment:
            WORDPRESS_DB_PASSWORD: example

    mysql:
        container_name: fbingenieria_db
        image: mysql:5.7
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: example
